version: '3'
services:
  
  common.mssql:
    image: "mcr.microsoft.com/mssql/server"

  common.rabbitmq:
    image: "rabbitmq:3-management"

#  shitpostbot.migrator:
#    image: skwig/shitpostbot/migrator
#    build:
#      context: .
#      dockerfile: ShitpostBot/ShitpostBot.Infrastructure.Migrator/Dockerfile

  shitpostbot.worker:
    image: ghcr.io/skwig/shitpostbot-worker:master
    restart: always
      
  shitpostbot.ml-service:
    image: ghcr.io/skwig/shitpostbot-ml-service:master
    restart: always